name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: ['macOS-latest', 'windows-latest']
        compiler: ['gcc']
        architecture: ['x86', 'x64']
        
        exclude:
          - os: macos-latest
            python-version: 3.6

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.architecture }} - ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable
          pip install setuptools wheel twine setuptools-rust
      
      - name: Build
        run: |
          python setup.py install
          python setup.py bdist_wheel --py-limited-api cp36
      
      # - name: Test
      #   run: cd test && python3 run_all.py

      - name: Publish
        if: success() && runner.os != 'Linux' && github.event_name == 'push'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/* --skip-existing